QAT:
    fully_quantized: False
    device: 'cuda'
    data_quantization:
      status: On
      bits: 8
      custom_bits: {}
      symmetric: On
      per_channel: True
      quantization_mode: 'static'
      observer: 'MovingAverage'
    weights_quantization:
      status: On
      bits: 8
      custom_bits: {}
      symmetric: On
      per_channel: False
      quant_and_freeze: True



    custom_quantization:

      - source_module: LlamaRMSNorm
        destination_module: compFlowRMSnorm

