QAT:
    fully_quantized: False
    device: 'cuda'
    data_quantization:
      status: On
      bits: 8
      custom_bits: {}
      symmetric: On
      per_channel: True
      quantization_mode: static
      observer: 'MovingAverage'
    weights_quantization:
      status: On
      bits: 8
      custom_bits: {}
      symmetric: On
      per_channel: True
      quant_and_freeze: True

    custom_quantization:
      - source_module: torch.nn.Linear
        source_name: "lm_head"
        destination_module: LinearQuant
        params:
          weights_quantizer:
            weight_bits: 16
          act_quantizer:
            act_bits: 16

      - source_module: torch.nn.Linear
        destination_module: LinearQuant
        params:
          weights_quantizer:
            group_size: 16
            weight_bits: qfloat4
          act_quantizer:
            group_size: 16
            act_bits: qfloat4
            act_dynamic: True
            observer: MinMax

      - source_module: LiteMLMatmul
        source_name: matmul_qkt
        destination_module: QuantMatmul
        params:
          quantizer_in1: # per token
            act_bits: 8
            act_symmetric: On
            dims: [ 0, -1 ]
            act_dynamic: True
            observer: MinMax
          quantizer_in2: # per tensor
            act_bits: 8
            act_symmetric: On
            dims: [ 0, -1, -2 ]
            act_dynamic: False
            observer: MovingAverage

      - source_module: LiteMLMatmul
        source_name: matmul_pv
        destination_module: QuantMatmul
        params:
          quantizer_in1: # per token
            act_bits: 16
            act_symmetric: On
            dims: []
            act_dynamic: False
            observer: MovingAverage
          quantizer_in2: # per tensor
            act_bits: 8
            act_symmetric: On
            dims: [ 0, -1, -2 ]
            act_dynamic: False
            observer: MovingAverage

