QAT:
    fully_quantized: False
    device: 'cuda'
    data_quantization:
      status: On
      bits: 8
      custom_bits: {}
      symmetric: Off
      per_channel: True
      quantization_mode: 'dynamic'
      observer: 'MinMax'
    weights_quantization:
      status: On
      bits: 8
      custom_bits: {}
      symmetric: Off
      per_channel: True
      quant_and_freeze: True

SmoothQuant:
  target_layers: {'input_layernorm': ['self_attn.q_proj', 'self_attn.k_proj', 'self_attn.v_proj'],
                     'post_attention_layernorm': ['mlp.up_proj', 'mlp.gate_proj']}
  alpha: 0.85
  scales_path: 'act_scales/llama-2-7b-hf.pt'