QAT:
    fully_quantized: False
    device: 'cuda'
    data_quantization:
      status: Off
      bits: 8
      custom_bits: {}
      symmetric: On
      per_channel: True
      quantization_mode: dynamic
      observer: 'MinMax'
    weights_quantization:
      status: Off
      bits: 8
      custom_bits: {}
      symmetric: On
      per_channel: False
      quant_and_freeze: True




    custom_quantization:

      - source_module: torch.nn.SiLU
        destination_module: compFlowSilU
