QAT:
    fully_quantized: False
    device: 'cuda'
    data_quantization:
      status: On
      bits: 8
      custom_bits: {'lm_head': 16}
      symmetric: On
      per_channel: True
      quantization_mode: dynamic
      observer: MinMax
    weights_quantization:
      status: Off
      bits: 4
      custom_bits: {'lm_head': 16}
      symmetric: On
      per_channel: True
      quant_and_freeze: False

    custom_quantization:

      - source_module: torch.nn.Linear
        destination_module: TrueQuantLinear
        params:
          weights_quantizer:
            weight_per_channel: True
            offline_quant_weights: True
          act_quantizer:
            act_dynamic: True
            observer: MinMax
